Update module_integration.yml to include change in master branch

diff --git a/.github/workflows/module_integration.yml b/.github/workflows/module_integration.yml
--- a/.github/workflows/module_integration.yml
+++ b/.github/workflows/module_integration.yml
@@ -37,55 +37,55 @@ jobs:
           mod-dir: " extern/noah-owp-modular/"
           targets: "surfacebmi"
       
-    - name: Init Submodules
-      run: git submodule update --init --recursive
+      - name: Init Submodules
+        run: git submodule update --init --recursive
 
-    - name: Cache Boost Dependency
-      id: cache-boost-dep
-      uses: actions/cache@v1
-      with:
-        path: boost_1_72_0
-        key: unix-boost-dep
+      - name: Cache Boost Dependency
+        id: cache-boost-dep
+        uses: actions/cache@v1
+        with:
+          path: boost_1_72_0
+          key: unix-boost-dep
 
-    - name: Get Boost Dependency
-      if: steps.cache-boost-dep.outputs.cache-hit != 'true'
-      run: |
-        curl -L -O https://boostorg.jfrog.io/artifactory/main/release/1.72.0/source/boost_1_72_0.tar.bz2
-        tar xjf boost_1_72_0.tar.bz2
+      - name: Get Boost Dependency
+        if: steps.cache-boost-dep.outputs.cache-hit != 'true'
+        run: |
+          curl -L -O https://boostorg.jfrog.io/artifactory/main/release/1.72.0/source/boost_1_72_0.tar.bz2
+          tar xjf boost_1_72_0.tar.bz2
 
-    - name: Build surfacebmi module
-      run: |
-        cmake -B extern/noah-owp-modular/cmake_build cmake_build -S extern/noah-owp-modular
-        cmake --build extern/noah-owp-modular/cmake_build --target surfacebmi -- -j ${{ env.LINUX_NUM_PROC_CORES }}
+      - name: Build surfacebmi module
+        run: |
+          cmake -B extern/noah-owp-modular/cmake_build cmake_build -S extern/noah-owp-modular
+          cmake --build extern/noah-owp-modular/cmake_build --target surfacebmi -- -j ${{ env.LINUX_NUM_PROC_CORES }}
 
-    - name: Build cfebmi module
-      run: |
-        cmake -B extern/cfe/cmake_build -S extern/cfe/
-        cmake --build extern/cfe/cmake_build/ --target cfebmi -- -j ${{ env.LINUX_NUM_PROC_CORES }}
+      - name: Build cfebmi module
+        run: |
+          cmake -B extern/cfe/cmake_build -S extern/cfe/
+          cmake --build extern/cfe/cmake_build/ --target cfebmi -- -j ${{ env.LINUX_NUM_PROC_CORES }}
 
-    - name: Build petbmi module
-      run: |
-        cmake -B extern/evapotranspiration/evapotranspiration/cmake_build -S extern/evapotranspiration/evapotranspiration/
-        cmake --build extern/evapotranspiration/evapotranspiration/cmake_build/ --target petbmi -- -j ${{ env.LINUX_NUM_PROC_CORES }}
+      - name: Build petbmi module
+        run: |
+          cmake -B extern/evapotranspiration/evapotranspiration/cmake_build -S extern/evapotranspiration/evapotranspiration/
+          cmake --build extern/evapotranspiration/evapotranspiration/cmake_build/ --target petbmi -- -j ${{ env.LINUX_NUM_PROC_CORES }}
 
-    - name: Build iso_c_fortran_bmi module
-      run: |
-        cmake -B extern/iso_c_fortran_bmi/cmake_build -S extern/iso_c_fortran_bmi
-        cmake --build extern/iso_c_fortran_bmi/cmake_build --target iso_c_bmi -- -j ${{ env.LINUX_NUM_PROC_CORES }}
+      - name: Build iso_c_fortran_bmi module
+        run: |
+          cmake -B extern/iso_c_fortran_bmi/cmake_build -S extern/iso_c_fortran_bmi
+          cmake --build extern/iso_c_fortran_bmi/cmake_build --target iso_c_bmi -- -j ${{ env.LINUX_NUM_PROC_CORES }}
 
-    - name: cmake_init_build
-      run: |
-        export BOOST_ROOT="$(pwd)/boost_1_72_0"
-        [ ! -d "$BOOST_ROOT" ] && echo "Error: no Boost root found at $BOOST_ROOT" && exit 1
-        cmake -B cmake_build -DBMI_C_LIB_ACTIVE:BOOL=ON -DBMI_FORTRAN_ACTIVE=ON -DNGEN_ACTIVATE_PYTHON:BOOL=OFF -S .
+      - name: cmake_init_build
+        run: |
+          export BOOST_ROOT="$(pwd)/boost_1_72_0"
+          [ ! -d "$BOOST_ROOT" ] && echo "Error: no Boost root found at $BOOST_ROOT" && exit 1
+          cmake -B cmake_build -DBMI_C_LIB_ACTIVE:BOOL=ON -DBMI_FORTRAN_ACTIVE=ON -DNGEN_ACTIVATE_PYTHON:BOOL=OFF -S .
 
-    - name: Build ngen
-      run: cmake --build cmake_build --target ngen -- -j ${{ env.LINUX_NUM_PROC_CORES }}
-      timeout-minutes: 15
+      - name: Build ngen
+        run: cmake --build cmake_build --target ngen -- -j ${{ env.LINUX_NUM_PROC_CORES }}
+        timeout-minutes: 15
 
-    - name: Run surfacebmi plus cfebmi
-      run: ./cmake_build/ngen data/catchment_data.geojson "cat-27" data/nexus_data.geojson "nex-26" data/example_bmi_multi_realization_config.json
-      
+      - name: Run surfacebmi plus cfebmi
+        run: ./cmake_build/ngen data/catchment_data.geojson "cat-27" data/nexus_data.geojson "nex-26" data/example_bmi_multi_realization_config.json
+        
       - name: Build ISO C Fortran BMI
         id: submod_build_2
         uses: ./.github/actions/ngen-submod-build
