Update GitHub Actions with job for MPI tests.

diff --git a/.github/workflows/test_and_validate.yml b/.github/workflows/test_and_validate.yml
--- a/.github/workflows/test_and_validate.yml
+++ b/.github/workflows/test_and_validate.yml
@@ -57,6 +57,58 @@ jobs:
     - name: cleanup_dir
       run: rm -rf cmake_build
 
+  test_mpi_remote_nexus_ubuntu_latest:
+    # The type of runner that the job will run on
+    runs-on: ubuntu-latest
+
+    # Steps represent a sequence of tasks that will be executed as part of the job
+    steps:
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - uses: actions/checkout@v2
+
+      # TODO: make sure this step is still necessary
+      - name: git submodule
+        run: git submodule update --init --recursive -- test/googletest
+
+      - name: Cache Boost Dependency
+        id: cache-boost-dep
+        uses: actions/cache@v1
+        with:
+          path: boost_1_72_0
+          key: unix-boost-dep
+
+      - name: Get Boost Dependency
+        if: steps.cache-boost-dep.outputs.cache-hit != 'true'
+        run: |
+          curl -L -O https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.bz2
+          tar xjf boost_1_72_0.tar.bz2
+
+      - name: Install MPI
+        id: install-mpi
+        run: |
+          apt-get update
+          apt-get install -y libopenmpi-dev openmpi-bin openmpi-common
+
+      - name: cmake_init_build
+        run: |
+          export BOOST_ROOT="$(pwd)/boost_1_72_0"
+          [ ! -d "$BOOST_ROOT" ] && echo "Error: no Boost root found at $BOOST_ROOT" && exit 1
+          cmake -B cmake_build -DMPI_ACTIVE:BOOL=ON -DBMI_C_LIB_ACTIVE:BOOL=OFF -S .
+
+      - name: build_tests
+        run: cmake --build cmake_build --target test_remote_nexus
+        timeout-minutes: 15
+
+      - name: run_tests
+        run: ./cmake_build/test/test_remote_nexus
+        timeout-minutes: 15
+
+      - name: clean_build
+        run: cmake --build cmake_build --target clean
+
+      - name: cleanup_dir
+        run: rm -rf cmake_build
+
   # Really do want this separate, as we want to test above that the shared lib isn't necessary to make things work.
   test_bmi_c_ubuntu_latest:
     # The type of runner that the job will run on
