Github Actions automated tests for Fortran BMI.

diff --git a/.github/workflows/test_and_validate.yml b/.github/workflows/test_and_validate.yml
--- a/.github/workflows/test_and_validate.yml
+++ b/.github/workflows/test_and_validate.yml
@@ -189,6 +189,91 @@ jobs:
       - name: cleanup_dir
         run: rm -rf extern/test_bmi_c/cmake_build
 
+  # As with the BMI C ubuntu job, separate to keep testing setups clean and cause of failures clear.
+  test_bmi_fortran_ubuntu_latest:
+    # The type of runner that the job will run on
+    runs-on: ubuntu-latest
+
+    # Steps represent a sequence of tasks that will be executed as part of the job
+    steps:
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - uses: actions/checkout@v2
+
+      - name: git submodule googletest
+        run: git submodule update --init --recursive -- test/googletest
+
+      - name: Cache Numpy Python Dependency
+        id: cache-linux-numpy-dep
+        uses: actions/cache@v1
+        with:
+          path: .venv
+          key: linux-numpy-dep
+
+      - name: Get Numpy Python Dependency
+        if: steps.cache-linux-numpy-dep.outputs.cache-hit != 'true'
+        run: |
+          python -m venv .venv
+          . .venv/bin/activate
+          pip install pip
+          pip install numpy
+          deactivate
+
+      - name: git submodule pybind11
+        run: git submodule update --init --recursive -- extern/pybind11
+
+      # TODO: do any steps need to be done here to install Fortran?
+
+      - name: cmake_init_test_lib_build
+        run: cmake -B extern/test_bmi_fortran/cmake_build -S extern/test_bmi_fortran
+
+      - name: build_test_bmi_fortran_shared_lib
+        run: |
+          cd extern/test_bmi_fortran/cmake_build
+          make
+          cd ../../../
+
+      - name: cmake_init_fortran_iso_c_lib_build
+        run: cmake -B extern/iso_c_fortran_bmi/cmake_build -S extern/iso_c_fortran_bmi
+
+      - name: build_test_fortran_iso_c_shared_lib
+        run: |
+          cd extern/iso_c_fortran_bmi/cmake_build
+          make
+          cd ../../../
+
+      - name: Cache Boost Dependency
+        id: cache-boost-dep
+        uses: actions/cache@v1
+        with:
+          path: boost_1_72_0
+          key: unix-boost-dep
+
+      - name: Get Boost Dependency
+        if: steps.cache-boost-dep.outputs.cache-hit != 'true'
+        run: |
+          curl -L -O https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.bz2
+          tar xjf boost_1_72_0.tar.bz2
+
+      - name: cmake_init_build
+        run: |
+          export BOOST_ROOT="$(pwd)/boost_1_72_0"
+          [ ! -d "$BOOST_ROOT" ] && echo "Error: no Boost root found at $BOOST_ROOT" && exit 1
+          cmake -B cmake_build -DBMI_C_LIB_ACTIVE:BOOL=ON -DBMI_FORTRAN_ACTIVE:BOOL=ON -DNGEN_ACTIVATE_PYTHON:BOOL=ON -S .
+
+      - name: build_bmi_fortran_tests
+        run: cmake --build cmake_build --target test_bmi_fortran
+        timeout-minutes: 15
+
+      - name: run_bmi_fortran_tests
+        run: |
+          cd ./cmake_build/test/
+          ./test_bmi_fortran
+          cd ../../
+        timeout-minutes: 15
+
+      - name: cleanup_builds
+        run: find . -name cmake_build -type d -delete
+
   test_unit_macos_latest:
     # The type of runner that the job will run on
     runs-on: macos-latest
@@ -312,6 +397,90 @@ jobs:
 
       - name: cleanup_shared_lib_dir
         run: rm -rf extern/test_bmi_c/cmake_build
+
+  test_bmi_fortran_macos_latest:
+    # The type of runner that the job will run on
+    runs-on: macos-latest
+
+    # Steps represent a sequence of tasks that will be executed as part of the job
+    steps:
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - uses: actions/checkout@v2
+
+      - name: git submodule googletest
+        run: git submodule update --init --recursive -- test/googletest
+
+      - name: Cache Numpy Python Dependency
+        id: cache-numpy-py3-dep
+        uses: actions/cache@v1
+        with:
+          path: .venv
+          key: unix-numpy-py3-dep
+
+      - name: Get Numpy Python Dependency
+        if: steps.cache-numpy-py3-dep.outputs.cache-hit != 'true'
+        run: |
+          python3 -m venv .venv
+          . .venv/bin/activate
+          pip install pip
+          pip install numpy
+          deactivate
+
+      - name: git submodule pybind11
+        run: git submodule update --init --recursive -- extern/pybind11
+
+      # TODO: do any steps need to be done here to install Fortran?
+
+      - name: cmake_init_test_lib_build
+        run: cmake -B extern/test_bmi_fortran/cmake_build -S extern/test_bmi_fortran
+
+      - name: build_test_bmi_fortran_shared_lib
+        run: |
+          cd extern/test_bmi_fortran/cmake_build
+          make
+          cd ../../../
+
+      - name: cmake_init_fortran_iso_c_lib_build
+        run: cmake -B extern/iso_c_fortran_bmi/cmake_build -S extern/iso_c_fortran_bmi
+
+      - name: build_test_fortran_iso_c_shared_lib
+        run: |
+          cd extern/iso_c_fortran_bmi/cmake_build
+          make
+          cd ../../../
+
+      - name: Cache Boost Dependency
+        id: cache-boost-dep
+        uses: actions/cache@v1
+        with:
+          path: boost_1_72_0
+          key: unix-boost-dep
+
+      - name: Get Boost Dependency
+        if: steps.cache-boost-dep.outputs.cache-hit != 'true'
+        run: |
+          curl -L -O https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.bz2
+          tar xjf boost_1_72_0.tar.bz2
+
+      - name: cmake_init_build
+        run: |
+          export BOOST_ROOT="$(pwd)/boost_1_72_0"
+          [ ! -d "$BOOST_ROOT" ] && echo "Error: no Boost root found at $BOOST_ROOT" && exit 1
+          cmake -B cmake_build -DBMI_C_LIB_ACTIVE:BOOL=ON -DBMI_FORTRAN_ACTIVE:BOOL=ON -DNGEN_ACTIVATE_PYTHON:BOOL=ON -S .
+
+      - name: build_bmi_fortran_tests
+        run: cmake --build cmake_build --target test_bmi_fortran
+        timeout-minutes: 15
+
+      - name: run_bmi_fortran_tests
+        run: |
+          cd ./cmake_build/test/
+          ./test_bmi_fortran
+          cd ../../
+        timeout-minutes: 15
+
+      - name: cleanup_builds
+        run: find . -name cmake_build -type d -delete
 
   # TODO: fails due to compilation error, at least in large part due to use of POSIX functions not supported on Windows.
   # TODO: Need to determine whether Windows support (in particular, development environment support) is necessary.
