Update test_and_validate.yml
Comment out the PET macos test runner.

diff --git a/.github/workflows/test_and_validate.yml b/.github/workflows/test_and_validate.yml
--- a/.github/workflows/test_and_validate.yml
+++ b/.github/workflows/test_and_validate.yml
@@ -924,65 +924,65 @@ jobs:
       - name: cleanup_builds
         run: find . -name cmake_build -type d -delete
 
-  # Run BMI C PET integration tests in MacOS environment, and separating to isolate
-  test_bmi_c_pet_it_macos_latest:
-    # The type of runner that the job will run on
-    runs-on: macos-latest
+#  # Run BMI C PET integration tests in MacOS environment, and separating to isolate
+#  test_bmi_c_pet_it_macos_latest:
+#    # The type of runner that the job will run on
+#    runs-on: macos-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v2
+#    # Steps represent a sequence of tasks that will be executed as part of the job
+#    steps:
+#      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+#      - uses: actions/checkout@v2
 
-      - name: Init Submodules
-        run: git submodule update --init --recursive
+#     - name: Init Submodules
+#        run: git submodule update --init --recursive
 
-      - name: cmake_petbmi_shared_lib_build
-        run: cmake -B extern/evapotranspiration/evapotranspiration/cmake_build -S extern/evapotranspiration/evapotranspiration
+#      - name: cmake_petbmi_shared_lib_build
+#        run: cmake -B extern/evapotranspiration/evapotranspiration/cmake_build -S extern/evapotranspiration/evapotranspiration
 
-      - name: build_petbmi_shared_lib
-        run: cmake --build extern/evapotranspiration/evapotranspiration/cmake_build/ --target petbmi -- -j ${{ env.MACOS_NUM_PROC_CORES }}
+#      - name: build_petbmi_shared_lib
+#        run: cmake --build extern/evapotranspiration/evapotranspiration/cmake_build/ --target petbmi -- -j ${{ env.MACOS_NUM_PROC_CORES }}
 
-      - name: Cache Boost Dependency
-        id: cache-boost-dep
-        uses: actions/cache@v1
-        with:
-          path: boost_1_72_0
-          key: unix-boost-dep
+#      - name: Cache Boost Dependency
+#        id: cache-boost-dep
+#        uses: actions/cache@v1
+#        with:
+#          path: boost_1_72_0
+#          key: unix-boost-dep
 
-      - name: Get Boost Dependency
-        if: steps.cache-boost-dep.outputs.cache-hit != 'true'
-        run: |
-          curl -L -O https://boostorg.jfrog.io/artifactory/main/release/1.72.0/source/boost_1_72_0.tar.bz2
-          tar xjf boost_1_72_0.tar.bz2
-      - name: cmake_init_build
-        run: |
-          export BOOST_ROOT="$(pwd)/boost_1_72_0"
-          [ ! -d "$BOOST_ROOT" ] && echo "Error: no Boost root found at $BOOST_ROOT" && exit 1
-          cmake -B cmake_build -DNGEN_ACTIVATE_PYTHON:BOOL=OFF -S .
+#      - name: Get Boost Dependency
+#        if: steps.cache-boost-dep.outputs.cache-hit != 'true'
+#        run: |
+#          curl -L -O https://boostorg.jfrog.io/artifactory/main/release/1.72.0/source/boost_1_72_0.tar.bz2
+#          tar xjf boost_1_72_0.tar.bz2
+#      - name: cmake_init_build
+#        run: |
+#          export BOOST_ROOT="$(pwd)/boost_1_72_0"
+#          [ ! -d "$BOOST_ROOT" ] && echo "Error: no Boost root found at $BOOST_ROOT" && exit 1
+#          cmake -B cmake_build -DNGEN_ACTIVATE_PYTHON:BOOL=OFF -S .
 
-      - name: build_bmi_c_Pet_IT_tests
-        run: cmake --build cmake_build --target compare_pet -- -j ${{ env.MACOS_NUM_PROC_CORES }}
-        timeout-minutes: 15
+#      - name: build_bmi_c_Pet_IT_tests
+#        run: cmake --build cmake_build --target compare_pet -- -j ${{ env.MACOS_NUM_PROC_CORES }}
+#        timeout-minutes: 15
 
-      - name: run_bmi_c_Pet_IT_tests
-        run: |
-          cd ./cmake_build/test/
-          ./compare_pet
-          cd ../../
-        timeout-minutes: 15
+#      - name: run_bmi_c_Pet_IT_tests
+#        run: |
+#          cd ./cmake_build/test/
+#          ./compare_pet
+#          cd ../../
+#        timeout-minutes: 15
 
-      - name: clean_build
-        run: cmake --build cmake_build --target clean
+#      - name: clean_build
+#        run: cmake --build cmake_build --target clean
 
-      - name: clean_shared_lib_build
-        run: cmake --build extern/evapotranspiration/evapotranspiration/cmake_build --target clean
+#      - name: clean_shared_lib_build
+#        run: cmake --build extern/evapotranspiration/evapotranspiration/cmake_build --target clean
 
-      - name: cleanup_dir
-        run: rm -rf cmake_build
-
-      - name: cleanup_dir
-        run: rm -rf extern/evapotranspiration/evapotranspiration/cmake_build
+#      - name: cleanup_dir
+#        run: rm -rf cmake_build
+#
+#      - name: cleanup_dir
+#        run: rm -rf extern/evapotranspiration/evapotranspiration/cmake_build
 
   # TODO: fails due to compilation error, at least in large part due to use of POSIX functions not supported on Windows.
   # TODO: Need to determine whether Windows support (in particular, development environment support) is necessary.
